modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/Evoslab/El-Huevo/issues"
[[mods]]
modId="elhuevo"
version="1.0.0"
displayName="El Huevo"
logoFile="elhuevo.png"
credits="Evo, EltrutLikes"
authors="Evo's Lab"
description='''
Adds El huevo (Egg Dog) to Minecraft!
'''

[[dependencies.elhuevo]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elhuevo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elhuevo]]
 modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"